# Site settings
title: EOS Amsterdam / Block Producer Candidate
email: eosamsterdam@monetashi.io
description: >- # this means to ignore newlines until "baseurl:"
  Building, operating and promoting the EOS infrastructure to help
  people organize into voluntary free-market communities securing
  life, liberty, and property for all.
url: https://www.eosamsterdam.net
baseurl: ''

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
permalink: pretty

# Languages
languages: ["en", "br", "es", "ko", zhs]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: en
languageNames:
  en: English (USA)
  br: Português (Brasil)
  es: Spanish
  ko: 한국어
  zhs: 中文
